# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 08610ccd1b4e6e86eda8444b4b976392b7921f8f26a67c0ef78ffebbeaca7dc2d07d4aa0c937242f8fafeafbe1c1ea5c9a717c1f10d09ec5e0c3b3939d84b1f7

test:
  secret_key_base: 16bec510acf679e6e57c9d2e3307aa0262a15ef31f247b4559e94ca6ff5de9705dc5b0c4259931a9169e48c9e45a68ac6d61da80b5d9d47a2114c5f414b8a1af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
